= Project: {Getting-Started-Brushless-DC-Motor}

=== Author: azmm12.
=== Email: {Abdulazizmmutiri@gmail.com} .
=== Date: 06/07/2022 .
=== Revision: version#1 .
=== License: Public Domain .

== Description of project:
Controlling Brushless DC Motor Using Electronic Speed Controller , the speed is adjusted by a potentiometer connected with arduino uno then the speed value is sent to the Electronic Speed Controller from Arduino .

== Installation Steps:
1. Use Fritzing Program because it has more access than Tinkercad .
2. Connect Arduino Uno and Brushless DC motor and ESC part and Battery and Potentiometer .
3. Download Servo Motor Library .
4. Write Code for Arduino to Control the process .
5. Upload Arduino code to Fritzing Program .
6. Simulate the Code .

=== Folder structure

....
 Main_Mission_1        => Arduino sketch folder
  ├── Main_1.ino       => main Arduino file
  ├── Main_Pic.png     => an image of the required schematics
  ├── Main_Task_1.fzz  => Fritzing file
  └── ReadMe.adoc      => this file
....
